/**
 * relationThemes.js
 * Color themes, avatars, and personality descriptions for each relation type
 */

export const RELATION_THEMES = {
  mother: {
    id: 'mother',
    label: 'Mother',
    emoji: '🌸',
    avatar: '👩',
    tagline: 'A warm embrace in every word',
    description: 'Caring, nurturing, and always ready to listen. She asks if you\'ve eaten and holds your heart safe.',
    // Tailwind color classes
    gradient: 'from-rose-300 via-pink-200 to-pink-100',
    darkGradient: 'from-rose-900 via-pink-900 to-pink-800',
    bubble: 'bg-pink-100 dark:bg-pink-950 text-pink-900 dark:text-pink-100',
    userBubble: 'bg-rose-400 text-white',
    accent: 'text-pink-600 dark:text-pink-300',
    border: 'border-pink-200 dark:border-pink-800',
    button: 'bg-pink-500 hover:bg-pink-600 text-white',
    card: 'from-rose-50 to-pink-100 dark:from-rose-950 dark:to-pink-900 border-pink-200 dark:border-pink-800',
    headerBg: 'from-rose-400 to-pink-500',
    dotColor: 'bg-pink-400',
    ring: 'ring-pink-400',
    inputFocus: 'focus:ring-pink-400',
    hex: '#f43f5e',
    lightHex: '#fce7f3',
  },
  father: {
    id: 'father',
    label: 'Father',
    emoji: '🌊',
    avatar: '👨',
    tagline: 'Steady guidance, unwavering love',
    description: 'Calm, wise, and always in your corner. He gives you strength when you need it most.',
    gradient: 'from-blue-300 via-sky-200 to-blue-100',
    darkGradient: 'from-blue-900 via-sky-900 to-blue-800',
    bubble: 'bg-blue-100 dark:bg-blue-950 text-blue-900 dark:text-blue-100',
    userBubble: 'bg-blue-500 text-white',
    accent: 'text-blue-600 dark:text-blue-300',
    border: 'border-blue-200 dark:border-blue-800',
    button: 'bg-blue-500 hover:bg-blue-600 text-white',
    card: 'from-blue-50 to-sky-100 dark:from-blue-950 dark:to-sky-900 border-blue-200 dark:border-blue-800',
    headerBg: 'from-blue-400 to-sky-500',
    dotColor: 'bg-blue-400',
    ring: 'ring-blue-400',
    inputFocus: 'focus:ring-blue-400',
    hex: '#3b82f6',
    lightHex: '#dbeafe',
  },
  brother: {
    id: 'brother',
    label: 'Brother',
    emoji: '🔥',
    avatar: '👦',
    tagline: 'Your ride-or-die, forever and always',
    description: 'Funny, loyal, slightly annoying but you love him. He\'ll tease you then have your back.',
    gradient: 'from-orange-300 via-amber-200 to-orange-100',
    darkGradient: 'from-orange-900 via-amber-900 to-orange-800',
    bubble: 'bg-orange-100 dark:bg-orange-950 text-orange-900 dark:text-orange-100',
    userBubble: 'bg-orange-500 text-white',
    accent: 'text-orange-600 dark:text-orange-300',
    border: 'border-orange-200 dark:border-orange-800',
    button: 'bg-orange-500 hover:bg-orange-600 text-white',
    card: 'from-orange-50 to-amber-100 dark:from-orange-950 dark:to-amber-900 border-orange-200 dark:border-orange-800',
    headerBg: 'from-orange-400 to-amber-500',
    dotColor: 'bg-orange-400',
    ring: 'ring-orange-400',
    inputFocus: 'focus:ring-orange-400',
    hex: '#f97316',
    lightHex: '#fed7aa',
  },
  sister: {
    id: 'sister',
    label: 'Sister',
    emoji: '💜',
    avatar: '👧',
    tagline: 'Your best friend wrapped in family',
    description: 'Fun, caring, and emotionally brilliant. She gets you, hypes you, and loves you unconditionally.',
    gradient: 'from-purple-300 via-violet-200 to-lavender-100',
    darkGradient: 'from-purple-900 via-violet-900 to-purple-800',
    bubble: 'bg-purple-100 dark:bg-purple-950 text-purple-900 dark:text-purple-100',
    userBubble: 'bg-purple-500 text-white',
    accent: 'text-purple-600 dark:text-purple-300',
    border: 'border-purple-200 dark:border-purple-800',
    button: 'bg-purple-500 hover:bg-purple-600 text-white',
    card: 'from-purple-50 to-violet-100 dark:from-purple-950 dark:to-violet-900 border-purple-200 dark:border-purple-800',
    headerBg: 'from-purple-400 to-violet-500',
    dotColor: 'bg-purple-400',
    ring: 'ring-purple-400',
    inputFocus: 'focus:ring-purple-400',
    hex: '#a855f7',
    lightHex: '#ede9fe',
  },
}

export const EMOTION_LABELS = {
  neutral: '😊',
  happy: '🥳',
  sad: '🥺',
  anxious: '😰',
  angry: '😤',
  bored: '😴',
  lonely: '🫂',
  proud: '🏆',
}
